name: POC18 CI Workflow

on:
  push:
    branches:
      - dev
      - test
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to DEV
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.DEV_EC2_KEY }}
          script: |
            cd /home/ec2-user/poc-18-multi-env-pipeline
            git checkout dev
            git pull origin dev
            sudo cp index.html /var/www/html/index.html
            sudo systemctl restart httpd

  deploy-test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to TEST
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.TEST_EC2_KEY }}
          script: |
            cd /home/ec2-user/poc-18-multi-env-pipeline
            git checkout test
            git pull origin test
            sudo cp index.html /var/www/html/index.html
            sudo systemctl restart httpd

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to PROD
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.PROD_EC2_KEY }}
          script: |
            cd /home/ec2-user/poc-18-multi-env-pipeline
            git checkout main
            git pull origin main
            sudo cp index.html /var/www/html/index.html
            sudo systemctl restart httpd
