name: POC18 CI Workflow

on:
  push:
    branches:
      - dev
      - test
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy index.html to DEV EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_KEY }}
          source: "index.html"
          target: "/tmp"

      - name: Deploy on DEV EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_KEY }}
          script: |
            sudo cp /tmp/index.html /var/www/html/index.html
            sudo systemctl restart httpd
            echo "DEV deployment successful"


  deploy-test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy index.html to TEST EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TEST_EC2_HOST }}
          username: ${{ secrets.TEST_EC2_USER }}
          key: ${{ secrets.TEST_EC2_KEY }}
          source: "index.html"
          target: "/tmp"

      - name: Deploy on TEST EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_EC2_HOST }}
          username: ${{ secrets.TEST_EC2_USER }}
          key: ${{ secrets.TEST_EC2_KEY }}
          script: |
            sudo cp /tmp/index.html /var/www/html/index.html
            sudo systemctl restart httpd
            echo "TEST deployment successful"


  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy index.html to PROD EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.PROD_EC2_USER }}
          key: ${{ secrets.PROD_EC2_KEY }}
          source: "index.html"
          target: "/tmp"

      - name: Deploy on PROD EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.PROD_EC2_USER }}
          key: ${{ secrets.PROD_EC2_KEY }}
          script: |
            sudo cp /tmp/index.html /var/www/html/index.html
            sudo systemctl restart httpd
            echo "PROD deployment successful"
